name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod -x ./gradlew

      - name: Run Backend tests and Checkstyle
        run : | 
              ./gradlew check

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Flush Checkstyle report on the status checks
        uses: l

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Backend with Gradle
        run: |
            ./gradlew build -x test

      - name: Publish Checkstyle Report
        uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        with:
          path: '**/build/reports/checkstyle/*.xml'